theme: jekyll-theme-leap-day

gem "github-pages", group: :jekyll_plugins

title: Kishan Mahabala Billava
description: I am interested in Deeplearning with Computer Vision  
show_downloads: "true"
github:
  repository_url: https://github.com/KishanBillava/
  zip_url: "www.linkedin.com/in/kishanbillava"
  tar_url: "https://medium.com/@kishanbillava73"

