theme: jekyll-theme-leap-day

gem "github-pages", group: :jekyll_plugins

title: Kishan Mahabala Billava
description: Python Artificial Intelligence Developer Deep Learning with Computer Vision  
show_downloads: "true"
github:
  repository_url: https://github.com/KishanBillava/

